### ISSUE TITLE
minluck not handling something right

### ISSUE THREAD

**Issue by AardWolf** [AardWolf/MHTimerBot#244]
```
[2022-01-11T16:50:24.718Z] Error executing dynamic command minluck TypeError: Cannot read property 'toLowerCase' of unde
    at Object.doMINLUCK [as execute] (/home/user/MHTimerBot/src/commands/minluck.js:69:39)
    at parseUserMessage (/home/user/MHTimerBot/src/MHTimer.js:614:44)
    at Client.<anonymous> (/home/user/MHTimerBot/src/MHTimer.js:265:21)
    at Client.emit (node:events:394:28)
    at MessageCreateAction.handle (/home/user/MHTimerBot/node_modules/discord.js/src/client/actions/MessageCreate.js:23:
    at Object.module.exports [as MESSAGE_CREATE] (/home/user/MHTimerBot/node_modules/discord.js/src/client/websocket/han
    at WebSocketManager.handlePacket (/home/user/MHTimerBot/node_modules/discord.js/src/client/websocket/WebSocketManage
    at WebSocketShard.onPacket (/home/user/MHTimerBot/node_modules/discord.js/src/client/websocket/WebSocketShard.js:443
    at WebSocketShard.onMessage (/home/user/MHTimerBot/node_modules/discord.js/src/client/websocket/WebSocketShard.js:30
    at WebSocket.onMessage (/home/user/MHTimerBot/node_modules/ws/lib/event-target.js:132:16)
```

**Comment by tehhowch** [comment]
Seems like a token list of length 0 got passed in

**Comment by AardWolf** [comment]
Might be related to the fact we allow `-mh minluck -d`
